<div class="columns">
  <div id="page:left" class="side-col">
    <h3><?php echo $this->escape($this->getTitle()) ?></h3>
    <?php $tabsList = $this->getTabs() ?>
    <?php if (is_array($tabsList) && !empty($tabsList)): ?>
    <ul class="tabs">
    <?php foreach ($tabsList as $tabName => $tab): ?>
      <li>
        <a class="tab-item-link" title="<?php echo $this->escape($tab->getLegend()) ?>" name="<?php echo $this->escape($tab->getName()) ?>" rel="<?php echo $this->escape($tab->getId()) ?>" href="#">
          <span>
            <span title="The information in this tab has been changed." class="changed"></span>
            <span title="This tab contains invalid data. Please solve the problem before saving." class="error"></span>
            <?php echo $this->escape($tab->getLegend()) ?>
          </span>
        </a>
      </li>
    <?php endforeach ?>
    </ul>
    <script type="text/javascript">
    /*<![CDATA[*/
    $(document).ready(function(){
        var links = $('ul.tabs li a.tab-item-link');
        links.click(function(event){
            event.preventDefault();

            links.removeClass('active');
            $(this).addClass('active');

            var element = $(this);
            // $(this).addClass('error');
            $('#content form .subform').hide().trigger('validate');
            $('#' + element.attr('rel')).parent().show();
            });

        $('#content form :input').live('change', function(event){
            var subform = $(this).parents('fieldset').attr('id');
            $(this).trigger('validate');

            $('ul.tabs li a.tab-item-link[rel='+subform+']').addClass('changed');
            });

//        $('#content form').live('validate', function(event){
//            $(':input', $(this)).each(function(){
//                $(this).trigger('validate');
//                });
//            });

//        $('#content form .subform').live('validate', function(event){
//            $(':input', $(this)).each(function(){
//                $(this).trigger('validate');
//                });
//            });

        links.first().click();
        });
    /*]]>*/
    </script>
    <?php endif ?>
  </div>
  <div id="content" class="main-col">
    <div class="main-col-inner">
      <div class="content-header">
        <table cellspacing="0">
          <tbody>
            <tr>
              <td style="width: 50%;"><h3 class="icon-head <?php echo $this->escape($this->getTitleClass()) ?>"><?php echo $this->escape($this->getEntityLabel()) ?></h3></td>
              <td class="form-buttons">
                <?php foreach ($this->getButtons() as $button): ?>
                <?php echo $button->setView($this)->render(); ?>
                <?php endforeach ?>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      <?php echo $this->renderForm() ?>
      <div class="content-header-floating" id="">
        <div class="content-header">
          <h3 class="icon-head <?php echo $this->escape($this->getTitleClass()) ?>"><?php echo $this->escape($this->getEntityLabel()) ?></h3>
          <p class="content-buttons form-buttons" style="">
            <?php foreach ($this->getButtons() as $button): ?>
            <?php echo $button->setView($this)->render(); ?>
            <?php endforeach ?>
          </p>
        </div>
      </div>
      <script type="text/javascript">
/*<![CDATA[*/
$(document).ready(function(e){
    $('.content-header-floating').hide();
    var position = $('.content-header').position().top;
    $(window).scroll(function(e){
        if (window.pageYOffset > position) {
            $('.content-header-floating').fadeIn();
        } else {
            $('.content-header-floating').fadeOut();
        }
        });

    var form = $('#content form');
    $('[class^=content-header] button[name=save]').click(function(){
        form.submit();
        });

    $('[class^=content-header] button[name=savecontinue]').click(function(){
        // FIXME: save and go back to the edit form
        form.submit();
    });

    $('[class^=content-header] button[name=delete]').click(function(){
        // TODO
        });

    $('[class^=content-header] button[name=reset]').click(function(){
        form.trigger('reset');
    });

    $('[class^=content-header] button[name=back]').click(function(){
        var url = new $.one.Url('admin/');
        document.location = url.toString([{name: 'action', value: 'index'}]);
    });

    $('[class^=content-header] button[name=duplicate]').click(function(){
        // TODO
        });

    });
/*]]>*/
      </script>
    </div>
  </div>
</div>