<div class="nav-bar">
<!--
    <ul id="nav">
                <li class="   level0"> <a class="" href="http://magento/index.php/admin/dashboard/index/key/7c9f28a9291a650631bbd7043cb71767/"><span>Dashboard</span></a>
                    </li>
                <li class="   parent level0" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Sales</span></a>
                                <ul>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/sales_order/index/key/5a23e7c47564e2bd4ce55655cff6d45e/"><span>Orders</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/sales_invoice/index/key/a390dbd4f03ea3c9cfed67444b1ad3fb/"><span>Invoices</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/sales_shipment/index/key/11b99cad0643ac3fc58a5ae27c1946d7/"><span>Shipments</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/sales_creditmemo/index/key/9eb929a3ff6f907dbde0ef556de6ba63/"><span>Credit Memos</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/checkout_agreement/index/key/0c6572b2084c65cbebc52631b8620917/"><span>Terms and conditions</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/oscommerce/adminhtml_order/index/key/34321f826a277ccac94ee12d350ec3c5/"><span>osCommerce Orders</span></a>
                    </li>
                <li class="   parent last level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Tax</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/tax_rule/index/key/311e2859a185433dc6421e41f4b7aad4/"><span>Manage Tax Rules</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/tax_rate/index/key/0b568ddc8faffab9ec2f0eed06707c1f/"><span>Manage Tax Zones &amp; Rates</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/tax_rate/importExport/key/f9a71badaa3e213a809ea8ecc1735345/"><span>Import / Export Tax Rates</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/tax_class_customer/index/key/813f46ce6fbb6586225376965ddfe2f9/"><span>Customer Tax Classes</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/tax_class_product/index/key/03d95f93d21324b2fd3e59443e665d6d/"><span>Product Tax Classes</span></a>
                    </li>
            </ul>
                    </li>
            </ul>
                    </li>
                <li class="   parent level0" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Catalog</span></a>
                                <ul>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/catalog_product/index/key/bd04d4c7e9482e74e669d87cc58f95cd/"><span>Manage Products</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/catalog_category/index/key/671a4524c1dac0171b3de550b1b3d0dc/"><span>Manage Categories</span></a>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Attributes</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/catalog_product_attribute/index/key/09f0bdeaebf008a4ae5e4510d2640181/"><span>Manage Attributes</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/catalog_product_set/index/key/284385ce8b73d110a6361140a785812e/"><span>Manage Attribute Sets</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/urlrewrite/index/key/45755e0617c6f3f4098f5c1681169226/"><span>URL Rewrite Management</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/catalog_search/index/key/220125ad8cc260369e1aee0417221d00/"><span>Search Terms</span></a>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Reviews and Ratings</span></a>
                                <ul>
                <li class="   parent level2" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Customer Reviews</span></a>
                                <ul>
                <li class="   level3"> <a class="" href="http://magento/index.php/admin/catalog_product_review/pending/key/3ab7b5ff1d877274fc05f2248ea0ed0f/"><span>Pending Reviews</span></a>
                    </li>
                <li class="   last level3"> <a class="" href="http://magento/index.php/admin/catalog_product_review/index/key/b6fe848e1b975a4b2ec7f6f3ae1568df/"><span>All Reviews</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/rating/index/key/77d4ffde678d2f0a2c7c2a9b32afc371/"><span>Manage Ratings</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Tags</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/tag/index/key/4f253a29c8b4e2fa91c71bc34c9533b3/"><span>All Tags</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/tag/pending/key/5c2e7c4f864e45db9630d7993adb01fa/"><span>Pending Tags</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Google Base</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/googlebase/types/index/key/aef4bbda0946b7f3a03353950152f910/"><span>Manage Attributes</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/googlebase/items/index/key/d47fa66754dd95d4a10071d5ca2ca3e9/"><span>Manage Items</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   last level1"> <a class="" href="http://magento/index.php/admin/sitemap/index/key/618db35fc8f2ffe80492bc3c2e18a600/"><span>Google Sitemap</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level0" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Customers</span></a>
                                <ul>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/customer/index/key/bf3da5520b87c79e0493053bfa609e1a/"><span>Manage Customers</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/customer_group/index/key/b4d3fe0e6ea070b02d63878407724825/"><span>Customer Groups</span></a>
                    </li>
                <li class="   last level1"> <a class="" href="http://magento/index.php/admin/customer_online/index/key/26cc1fcc1046ecdd4aad52573589a1ff/"><span>Online Customers</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level0" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Promotions</span></a>
                                <ul>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/promo_catalog/index/key/07c1e18a695c9a21d6a5a4f5fd771b60/"><span>Catalog Price Rules</span></a>
                    </li>
                <li class="   last level1"> <a class="" href="http://magento/index.php/admin/promo_quote/index/key/962977c4caeccbc49802dae90cb17914/"><span>Shopping Cart Price Rules</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level0" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Newsletter</span></a>
                                <ul>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/newsletter_template/index/key/493e9c1fb18727b5a97cd1f235fbb400/"><span>Newsletter Templates</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/newsletter_queue/index/key/9cf47a42583168646eee177ccd50ddd6/"><span>Newsletter Queue</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/newsletter_subscriber/index/key/87383726a700136abf159000f8f91a4d/"><span>Newsletter Subscribers</span></a>
                    </li>
                <li class="   last level1"> <a class="" href="http://magento/index.php/admin/newsletter_problem/index/key/0e170caa55957a68d464a4c596711e32/"><span>Newsletter Problem Reports</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level0" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>CMS</span></a>
                                <ul>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/cms_page/index/key/e4716fa1915570737623c4bf3ed71568/"><span>Pages</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/cms_block/index/key/7c3bb3defd7faddf9b533073d943bad3/"><span>Static Blocks</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/widget_instance/index/key/c16a5f18eb81a7192e4b997e3aae6f32/"><span>Widgets</span></a>
                    </li>
                <li class="   last level1"> <a class="" href="http://magento/index.php/admin/poll/index/key/c7f2e5dd69d53f0dec6218d1c64eb3e0/"><span>Polls</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level0" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Reports</span></a>
                                <ul>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Sales</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_sales/sales/key/6c99b606a64da41df2fd6f18bab68709/"><span>Sales</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_sales/tax/key/ee1443e88bff050a29826aa5df83504a/"><span>Tax</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_sales/shipping/key/68ee16e02d7d3a1c738e4cad41d98885/"><span>Shipping</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_sales/invoiced/key/789a78dab74008ae8cc6b96393ed99ad/"><span>Total Invoiced</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_sales/refunded/key/341baae8f177f6e4b007a18da7f1de57/"><span>Total Refunded</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/report_sales/coupons/key/ca73ebdc70a4f93a5e5bc6d980d78c17/"><span>Coupons</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Shopping Cart</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_shopcart/product/key/1cf1e8bfb351ea196c493488246c27e5/"><span>Products in carts</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/report_shopcart/abandoned/key/30696b4848de505a807fd792e160b1a8/"><span>Abandoned carts</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Products</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_sales/bestsellers/key/ce240421609d1f371fab4ec7f4d4eac5/"><span>Bestsellers</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_product/sold/key/8b1a08b170ca42240c517111286fa94d/"><span>Products Ordered</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_product/viewed/key/45457895807de9777d4a26cd60adab66/"><span>Most Viewed</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_product/lowstock/key/d8251461d7330b21e29fa4067e3150a4/"><span>Low stock</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/report_product/downloads/key/2e41fa0b13fef29636ee55d481edf333/"><span>Downloads</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Customers</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_customer/accounts/key/8d2dca11b5b4aa7472874b59317ad1b9/"><span>New Accounts</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_customer/totals/key/c8a2f2aa38ef4c9f3ce9c1af31b75fb8/"><span>Customers by orders total</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/report_customer/orders/key/3a86170a5a9e8b610ecf8748db152366/"><span>Customers by number of orders</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Reviews</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_review/customer/key/99d1074b1e4a7ef809316d29a0785f23/"><span>Customers Reviews</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/report_review/product/key/74d0bbb36ce2ff0e5c80f44c60b99017/"><span>Products Reviews</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Tags</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_tag/customer/key/aa7041cae640beec91272077cc838001/"><span>Customers</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/report_tag/product/key/f52a0c2f8844f574e28611ff072b10ed/"><span>Products</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/report_tag/popular/key/4ae19d2ad7789c1c63be6bf785c17eff/"><span>Popular</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/report/search/key/5a93bd8bbcd7dda7e6c362ebdb20ff12/"><span>Search Terms</span></a>
                    </li>
                <li class="   last level1"> <a class="" href="http://magento/index.php/admin/report_statistics/index/key/b70d00d9597d0b326a9cf8c9756b1068/"><span>Refresh Statistics</span></a>
                    </li>
            </ul>
                    </li>
                <li class="  active  parent level0" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="active" onclick="return false" href="#"><span>System</span></a>
                                <ul>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/system_account/index/key/dee55d3026ebfd0e309ca5759be30be2/"><span>My Account</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/notification/index/key/b14425988aece32dcdaf6071542bdb99/"><span>Notifications</span></a>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Tools</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/system_backup/index/key/4ee3f2f04487e518cce277806edd44c8/"><span>Backups</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/compiler/process/index/key/bc9f915f1e363c156783e5008c98b299/"><span>Compilation</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Web Services</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/api_user/index/key/7d7df102bb89f1e13b30001f21bddab1/"><span>Users</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/api_role/index/key/6e213fc965a81c427f87c737a31a03cf/"><span>Roles</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/system_design/index/key/7a8a2502fbbe4e6e43c0c2cce4158de0/"><span>Design</span></a>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Import/Export</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/system_convert_gui/index/key/a726ce15a51e4cd5391995ac08cf9286/"><span>Profiles</span></a>
                    </li>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/system_convert_profile/index/key/a9743555a386a9e69e3ee7120c76f7c9/"><span>Advanced Profiles</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/oscommerce/adminhtml_import/index/key/b85dc2eed92c7dc024483626b7ecd8a2/"><span>osCommerce</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/system_currency/index/key/76fb921f64f6a9206139596c49c980cd/"><span>Manage Currency Rates</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/system_email_template/index/key/d83d1744d4c504a81af94e931ed39061/"><span>Transactional Emails</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/system_variable/index/key/1db7dcfcf89ba4cf620374d131b8fdf6/"><span>Custom Variables</span></a>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Permissions</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/permissions_user/index/key/54a996fc78fc591be2a11e61f50a2ad1/"><span>Users</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/permissions_role/index/key/64b7e4b1f9f1cc38bc38391d4d60e2b1/"><span>Roles</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   parent level1" onmouseout="Element.removeClassName(this,'over')" onmouseover="Element.addClassName(this,'over')"> <a class="" onclick="return false" href="#"><span>Magento Connect</span></a>
                                <ul>
                <li class="   level2"> <a class="" href="http://magento/index.php/admin/extensions_local/index/key/216c83471769924eea8d9ebb547c9b60/"><span>Magento Connect Manager</span></a>
                    </li>
                <li class="   last level2"> <a class="" href="http://magento/index.php/admin/extensions_custom/index/key/968dad5f9ac30d193ab386cc6446451f/"><span>Package Extensions</span></a>
                    </li>
            </ul>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/cache/index/key/0b26602d9dc0aa816bcff535deb97f8a/"><span>Cache Management</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/process/list/key/cb91222a76aeb0b3d47f9ace88c551d5/"><span>Index Management</span></a>
                    </li>
                <li class="   level1"> <a class="" href="http://magento/index.php/admin/system_store/index/key/8a2ee30924a630b48b75de61a5f496ca/"><span>Manage Stores</span></a>
                    </li>
                <li class="   last level1"> <a class="" href="http://magento/index.php/admin/system_config/index/key/336890e8ed6378de77eae40b22d9f7d4/"><span>Configuration</span></a>
                    </li>
            </ul>
                    </li>
            </ul>

    <a href="http://www.magentocommerce.com/gethelp/en_US/Mage_Adminhtml/system_account/index/" id="page-help-link" target="magento_page_help">Get help for this page</a>
    <script type="text/javascript">$('page-help-link').target = 'magento_page_help'</script>

-->
</div>