<script type="text/javascript">
$(document).ready(function(){
    $('.nav-bar #nav li.parent').hover(
        function(){
            $(this).addClass('over');
            },
        function(){
            $(this).removeClass('over');
            }
        );
    });
</script>
<div class="nav-bar">
  <ul id="nav">
  <?php if (is_array($children = $this->getAllChildNodes())): ?>
    <?php $count = count($children); ?>
    <?php $classes = array('level0'); ?>
    <?php foreach ($this->getAllChildNodes() as $child): ?>
      <?php if (--$count <= 0): ?>
        <?php $classes[] = 'last' ?>
      <?php endif ?>
      <?php echo $child->setMoreClasses($classes)->render('navigation/item.phtml'); ?>
    <?php endforeach ?>
  <?php endif ?>
  </ul>
  <a href="http://github.com/gplanchat/one.platform/wiki" id="page-help-link" target="magento_page_help">Get help for this page</a>
  <script type="text/javascript">$('#page-help-link').target = 'magento_page_help'</script>
</div>