<div id="messages">
  <ul class="messages">
  <?php foreach ($this->getAllErrors() as $message): ?>
    <li class="error-msg"><?php echo $this->escape($message)?></li>
  <?php endforeach ?>
  <?php foreach ($this->getAllWarnings() as $message): ?>
    <li class="warning-msg"><?php echo $this->escape($message)?></li>
  <?php endforeach ?>
  <?php foreach ($this->getAllNotices() as $message): ?>
    <li class="notice-msg"><?php echo $this->escape($message)?></li>
  <?php endforeach ?>
  <?php foreach ($this->getAllInfos() as $message): ?>
    <li class="success-msg"><?php echo $this->escape($message)?></li>
  <?php endforeach ?>
  </ul>
</div>