<?php if (!$this->getSession()->isEmpty()): ?>
<p class="super">
  <?php //echo $this->translate('Logged in as %s', $this->getUser()->getUsername()) ?>
  <?php echo sprintf('Logged in as %s since %s', $this->getUser()->getUsername(), date('D d, M - H:i:s', $this->getLogonTime())) ?>
  <span class="separator">|</span>
  <?php echo date('D d, M - H:i:s', time()) ?>
  <span class="separator">|</span>
  <a class="link-logout" href="<?php echo $this->url(array('action' => 'logout'), 'account')?>"><?php echo $this->translate('Log Out') ?></a>
</p>
<?php endif ?>