<div class="range">
  <div class="range-line">
    <span class="label">From:</span> <input type="text" class="input-text no-changes" value="" id="<?php echo $this->escape($this->getField())?>-from" name="<?php echo $this->escape($this->getField())?>[from]">
  </div>
  <div class="range-line">
    <span class="label">To : </span><input type="text" class="input-text no-changes" value="" id="<?php echo $this->escape($this->getField())?>-to" name="<?php echo $this->escape($this->getField())?>[to]">
  </div>
</div>