<?php echo $this->doctype() ?>
<?php $this->headLink()->setStylesheet($this->getStyleUrl('css/layout.css'))?>
<html>
  <head><?php echo $this->renderChild('head')?></head>
  <body<?php if (count($this->getBodyClasses()) > 0):?> class="<?php echo $this->renderBodyClasses() ?>"<?php endif?>>
    <div class="layout">
      <div class="main">
        <?php echo $this->renderChild('body') ?>
      </div>
      <div class="header">
        <?php echo $this->renderChild('header') ?>
      </div>
      <div class="column-left">
        <?php echo $this->renderChild('column-left') ?>
      </div>
    </div>
    <div class="copyright">Powered by XNova:Legacies and One.Platform</div>
  </body>
</html>